* Monday, 10/28/2019

** 10:39
Just realized that all parallel parts when loaded on version 0.35 crash the raspberry pi program. First I tested a fresh install with the latest update which is on the website, version 0.35, and the parallel IO parts crash. Then, I checked Brittany's pi, which has version 0.0, a beta version I think, actually worked. Must have not been updated in a while. Then I tested Imre's pi. On the 18th, I was here with Isaac when he went and updated that pi, and that is the same day that version 0.35 came out. It doesn't load chips with parallel IO.

** 10:44
Going to ask Kristen who got shipped Pi's between now and the 18th. Trying to find the ones that are out there with version 0.35 on them.

** 11:11
Done checking all the Pis that are here and ready to ship. Three in the shipping room and four on the rack. The only ones that are affected are the other two that I put together and updated last Thursday. Going to need to notify people that if they have version 0.35, using parallel IO requires manual intervention.

** 11:13
Erik wrote the checklist on the board:

1. Understand the bug
2. Who is impacted?
3. Contain the issue
4. Notify the impacted
   - w/ the solution, ideally
5. Fix + Roll out fix
6. Review any processes needed to be sure it doesn't happen again 

** 11:14
I also have Imre's pi with me which has some problems. The problem is that he needs version 0.35 to use the $I^2C$ functionality that Isaac added in that version. For now, I will keep his on 0.35 until the problem is fixed and hope he doesn't run into the problem. If he does run into before it is sorted out, we will just give him another pi on v0.34. No problem.

** 11:25
Now I am going to update the AWS bucket to have the working version, v0.34, as the latest for download from the website.

** 12:52
Just got back and made sure that the website was updated with the latest version as v0.34. I think chrome remembered what I downloaded or kept v0.35 in the cache because it kept downloading the old one even after I uploaded the new one. Firefox was the way to go. Confirmed by putting the file on a USB and loading it into the pi updates screen. Version 0.34 is up.

** 12:57
Going through GitLab now to see if I can find any commits that Isaac made for version 0.35 that might seem to affect any IO stuff.  

** 13:59
Okay I am going to try and plan a bit. I was just looking at the GitLab history for [[file:~/Documents/programit/ProgramItKivy-1/ProgramIt/LibBaseProgPart.py::from%20.%20import%20LibIO][LibBaseProgPart.py]] and also for [[file:~/Documents/programit/ProgramItKivy-1/ProgramIt/LibIO.py::try:][LibIO.py]]. I know that the =get-spi-bus-info= is the last thing to be called and is what throws a "=AttributeError: 'NoneType' object has no attribute 'fileno'"= The reason is because curtain SPI values are only set if the =io_type= is =IO_SPI=, and the type of the parallel parts is IO_PIN, thereby several variables are left with the =None= value. Going to look for "raspi" and "fileno".

** 14:06
Ok so this is the code that is throwing the error for sure. 

 #+begin_src python
    elif israspi():
        name = os.readlink("/proc/self/fd/" + str(spi_obj.fileno()))
 #+end_src
 [[file:~/Documents/programit/ProgramItKivy-1/ProgramIt/LibIO.py::elif%20israspi():][link]]

This bit of code is only run if it is on a raspberry pi and the =spi-obj= is what is =None= when trying to load an =IO_PIN= part.

** 14:10
Going to try and recreate the situation on the pi and then get to the crash log file.

** 14:22
Just copied over the crash files via USB. [[file:/media/cole/2612-8E18/crash-2018-08-23_16.01.08.log][Latest one]]

** 14:38
I was slightly wrong, the code above is actually not supposed to run. The =spi_obj= is supposed to be a =PinIoObject= instead of =None=. 

** 15:48
Trying to setup Emacs as my python IDE. Using [[https://realpython.com/emacs-the-best-python-editor/#emacs-for-python-development-with-elpy][this website]]. 
** 16:06
I need to learn how to use magit. Also need to get my org agenda system rolling again, that would be awesome.
** 16:14
Emacs and elpy is so freaking cool. Need to learn [[https://elpy.readthedocs.io/en/latest/ide.html#navigation][these navigation commands]]. Heck yeah.
** 16:29
What's my literate development environment going to look like? 
Well I am going to think about what to ask Isaac next. I could look into his problem more and I would be learning how his code works, but it may not be very time-efficient.

** 17:09
Just experimented with magit. Asked Erik about getting a key and a monitor or two. I actually want to get a monitor for home also on another note. Now that I have the kernel updated I can actually use this laptop at home.  

