* Thursday, 10/24/2019
** 10:23
This is the first journal entry on the XM Dropbox account. Sweet. 
** 12:51
Just got Kivy 1.9.1 to work with Isaacs ProgramIt code. Boom. The UI is a little off because of the High DPI display.

** 13:00
Talking about chips and setting registers. "Register Map" is what specifies blocks of the (volatile) chip memory with a register name, and accessibility and stuff. It's important to know that it is volatile.

** 13:03
SPI. three lines.

Data line: which sends the register "address" and the value for the address. 
Clock line:
Latch line: LE. 

Shift registers. It's the input buffer.

** 13:11
What are the "Gotcha's"

1. Where to I write it
2. What values to write
3. What order to write them
   - set frequency before amplitude? 

Creating a framework to account for the order which some things should be written, specific to different chips. The user doesn't have to know about any of it. 

# Google UART (Erik doesn't think we use this)

** 13:42
Just sat down with Brittany who showed me how she tests the chips.

** 16:06
Amazon Web Services

Resources: 
S3 - Storage
RDS - Database services
EC2 - Compute
Route 53 - Domain names
IAM - Identity management


EC2:
t3a.medium is an example instance type. 
Data center is in the west coast
IP Address of the website:  34.214.180.12

Route 53: (domain names)
Just showed me aliases

S3:
Raspberry Pi update files: "xmicro-assets"
Amazon S3 > xmicro-assets > public-raspi-images

** 17:54
AWS online training material, Erik will cover the cost. 
