* Thursday, 11/14/2019
** DONE fix blockbuilder SVG lines
SVGs export with lines when two objects share the same edge. The ideal solution would be to join the polygons together to create on svg image. The layers of the files could be separated and then joined by clipping out some background layer and then using that clipped layer as a mask. Need to fiddle with the layers of the existing part SVGs and practice cutting and masking in inkscape and with code.

Do SVGs merge when placed near eachother? Polygons with static or open edges?
** 17:35
Okay. Erik just left. Going to write to myself at the end of today and maybe I should do this every day at the end. Went through a bunch of IT stuff today. Took out a server computer and installed windows server 2019 on it and then put it on the rack. That was pretty fun/cool. I also looked at the cascade tool a bit more today when I first got here. I just made it so that the lines are less visible when you zoom out on the svgs.

** 17:37
Isaac comes in tomorrow so I should probably have some questions for him. I do really want to know where the .json file is located that stores all the parts. In the Portainer version of CASCADE_DB? I know the SVGs are referenced from the S3 bucket. 

- cascade database parts location? How to manually edit? 

The actual location and not just how to add them through the form factor or database tool. One thing I should probably do is commit and push my changes to the blockbuilder.

** 17:47
Done with that. What else might I want to wrap up before tomorrow? I started setting up the phone today also. Need to finish that sometime. The instructions are somewhere.

** 18:25
Still trying to get this phone to provision. Doesn't seem to be working and I think it is because the software is old. I can update it next time or I guess right now I could. Have I thought of most everything for tomorrow?   
