* Friday, 12/27/2019
** IT [2/8]
*** DONE [#A] John's Laptop
** Cascade [3/10]
*** DONE Export filemaker parts to cascade
** FileMaker
*** DONE Read parametric data into cascade json export
Erik set up the property metadata in the format: order|show|variation (e.g. 2|1|0). Variation isn't used right now. Took me a while to get the data read and interpreted correctly. I just excluded the ones that have show = 0 and then sorted them by the order value. I used the "filter" and "sort" functions in a portal in filemaker. When the parts data is exported, it goes down the already sorted portal fields and writes them in that order. (The script does not care about the order or show information, only the portal does)    

*** DONE Use units in cascade as defined in FileMaker
I added some units to the cascade units lookup table. I needed this table to transfer existing units that the website uses to the format that cascade accepts. I added:
- Resistance, Ohms
- Capacitance, F
- Depth, in.
- Freq Accuracy, ppm

** Controller [1/11]
*** DONE [#A] A8F2 (PE43508)
** Emacs/Misc [2/3]
** 15:01
Just talked to Linda at CDW. Order number LDBN9Z0. Quoted us for 4 16-core windows server 2019 licenses, 5 CALs, 5 copies of Windows 10 Pro, and vSphere essentials. Total was $5690. Then we took off two of the 16 core copies and bought that. $177.80 per Windows 10 Pro copy. $915 for each 16-core Windows Server, $39 per CAL, and $512 for Essentials. She also said that Essentials Plus was $4600.

When I called Microsoft earlier this week, they said that it was $972 for each Windows Server license and $263 per CAL. Much more expensive than it was through CDW. The Microsoft Server specialist number they gave me was 800-456-3355
** 15:44
Installed EMPro 2017 and SystemVue 2018 on John's new laptop.  All the things that were written down on this note are:
- ADS 2019
- Genesys 2018
- +SystemVue 2018+
- +EMPro 2017+
- Solidworks 2018
- QuickBooks
- Microsoft Office

I am waiting for Michael Sparling to get in and help me with the Solidworks install.

** 15:46
The MAC address of John's computer needed to be spoofed to be: 5A4D5700ADA1. 

** 15:48
Three things that John needed to be running on his Acer laptop last week are:
- Microsoft Office
- WiFi
- Additional Displays
** 15:53
I changed "PCB Active" for A6F4 to "Y". It was called for in a cascade file (meaning it used to be on cascade) and it was ready for export otherwise. Now it will be on cascade.

** 15:57
I was thinking about putting the PCB svg files in the file manager database but decided we could just sync from the E_drive Website_Assets folder to the folder in the s3 bucket.

** 16:09
Need to change a bunch of parts in the XMWcontroller to have the correct part names. A5N5 needed to be changed from 0604 to 0409, for example.
** 17:04
