* Friday, 10/25/2019
** 08:52
There are two Repl environments that Isaac created for the ProgramIt app. =Replshell= and =CommandTerminal=.

To find the part in the code that listens for the CommandTerminal.py script, use: ~grep -iRn rpc_port .~

** 08:58
os.truncate [[https://docs.python.org/3/library/os.html]] 
To make the raspberry pi image Isaac went into gparted on the pi and shrunk down the partition before copying the whole OS.

** 09:11
Figure out CommandTerminal using the help page. From there you can figure out everything else.

** 09:13
LTS version of Node.js, version 10. I have version 8 and it works with Cascade. Isaac says 10 won't work. 

** 09:43
part_ADF41XX 

tab_layout is where resizing and GridLayout stuff is. 

Mix-ins are in CustomWidgets.py
Commonly used colors are in CustomWidgets.py

"Snapped" makes things (borders/text) look crisp. Prevent splitting pixels.

BaseProgWithRegs.py is higher up, composes the UI elements. 

UserDataViewHelpers.py 
    - DataContext
    - BaseDataViewHelper

BaseRegPart.py: handles everything
    - def set_data() function
      - data_tgt.push() and pull()

RegisterContext and RegisterTarget
DataContext and DataTarget

BaseProgPart, only part code not in partmods folder, is abstract for every part.

** 11:21
New Part: ADRF-5740, XM-B7P2-0804D 

** 15:42
Isaac showing me BlockBuilder. Made with Node.js just like Cascade but he says the code is much more modern. Eventually Cascade should be that way.

** 15:44
Dimensions of the chips are in the last numbers. XM-B1N5-0609D is 6 x 9 XM units. 1 XM unit = 0.135 in. It's a mixer. RF is the High frequency (radio frequency), RF = IF + LO. The basic mixer is used as a transmitter or a receiver.     
