* Friday, 01/24/2020
** 10:22
Just got the one click export to work in filemaker. Every script works out of E_drive. To successfully be able to add to the layout tool, you need to run filemaker on a machine with the following:
- map E_Drive to E:
- install node.js
- install awscli
- authenticate aws cli
  using =aws configure= and entering credentials from AWS IAM

** 11:07
VMW_UUID=1B294D56-713D-59AF-CE15-523C64B71206
** 15:31
John wants me to do something. I need to make a list of the categories that work in cascade. The thing is that they all /work/, but the data that is in the tool is not all sorted out. It's going to be a lot of manual editing. I could go in and do that myself - and I probably should. Some amount of time each day should be spend fixing the data in cascade, and some should be spent adding formfactors. That is the more easy but boring things that simply need to get done. Another part of the day should be spent coming up with plans for future upgrades or things to get done. The TODO management. And maybe another part would be working on more algorithmic tasks. That pretty much is the same thing as planning, if you really want to generalize it. Alright.

** 15:46
I was talking about John and what he wants me to do. Basically my answer is that there is not a category on cascade that doesn't work. It's not a simple yes or no answer. If you insist on a simple yes or no answer, the answer is no. It's a properly build machine with dirty input data. The dirty data is a result of lots of things not even just the filemaker. Things in sharepoint are not consistent and changes get made accidentally that combine data together. It is dirty data. I am more than willing to go through and help fix that. It is going to take some time. Cascade is finished. 


** 16:34
** 16:36
