* Saturday, 01/25/2020
** 11:34
The actual product number and verification code for quickbooks 2020 are:
- Product Number: 239629
- Verification Code: 203948

** 14:54
[[https://support.microsoft.com/en-us/help/20510/windows-10-connect-to-vpn][Windows 10 VPN Info]]
** 19:17
I am at iHop talking with Markus. He is talking about what I need to get for my ar. I should probably Get new iron sights because the ones that ge gave me don't work very well.

** 19:21
It's just a vibe check dude. Markus is asking me if I want to go to the country.   
** 19:41
Just tried to DDOS the iHop wifi. Haha. It didn't work though. I wonder what technology exists that protects against that.

** 19:45
Taylor sometimes wants to go on a diet and thinks she is going to go to the gym and be vegan and stuff. Markus thinks she should be more reasonably with your expectation.

** 19:47
I just burped in Markus' face and I am sorry about that. Talking about having far off goals.

** 19:59
"No, let me escape" Markus said. I sent him an apartment that we might go look at tomorrow. He is looking at memes right now.
