* Monday, 01/27/2020
** 09:38
This is my sticky note. 
- Desktops: 11
- Laptops: 7
- Pis: 4
- Legacy Machines: 2
- Misc: 10 or so
- Printers: 4 or so

DESKTOP-IN3NHCH
- A7V1
- B5E6
** 10:03
** 11:14
Thinking about telling Erik that I don't want to continue learning about how to make a node js server and try out the datatables thing. I think that I can do this on my own time and learn how all this stuff works and then try it. The question is, do I have to use a Node server to do this? Can I test out the thing without it? Maybe I can just copy the cascade stuff. Or the blockbuilder stuff? Going to see.

** 12:49
Just got back from lunch. Going to take a look at the things that I need to do.
** 12:52
Going to go over the stuff in the email now. RMM is the remote management software that they want to put on our computers. I guess that this would be important but I am not really in love with that idea. I don't think that we need this. It is pretty cheap though, so it might not be an issue. Veeam is a backup thing.

** 13:05 Sigma conversation
Some questions I will want to ask..

- High availability. Is Zerto necessary? What is Zerto exactly? What is the different betweent that and simply swapping hardware components if a server fails?

- RMM. What is the purpose of remotely managing things? Not all computers?

** 15:32 
Pull the drives, have to pull the PERC as well. Cannot have a container mismatch.

** 15:37
Failing drives -> RAID 6 allows two to fail.

RMM will give you statistics on infrastructure.

** 15:43
- Recovery data objective
- Recovery time objective

Zerto: Fancy Mirroring Software.

$2 a day insurance.

** 15:52
Backup versus HA.
** 17:43
** 19:17
Talking to Markus at iHop again.
This is pretty cool and I think that it is the best thing since sliced bread. That was a test of how fast I can type. I think that the mouse is a thing of the past. Shouldn't need to use the mouse at all pretty cool, yo.

** 20:03
I think that this is pretty cool. I think that it is important to be able to type fast. Typing fast is pretty cool. I can also edit what I type pretty fast. I think science is cool.

** 20:22
Markus is talking to Taylor right now. It think that it feels good to just type on my computer. Got to just use no mouse. That is what makes typing so much better.
** 20:53
Markus really wants to have the emotional maturity conversation
lnlkNarl/nkgbl.egtk.jkaegeay;8ogaruoaerg.uhawwlfugawfliuahrefluhrugrihogirehgiogr I ate two of my chicken. Chicken. That's so cool. hehe. That was a little bit ore typing that that. what I said. He is very conscious of the things that he is saying. You aren't typing your face is...

** 21:40
Unless you are typing, you must be too preoccupied. I can't really read your expression.

** 21:40
He hates this. Narrate to me. this is a shitty account of real life events

** 22:09
Markus is Swedish

** 23:03
I was just moving my arms around strangely. I think I am trying to say stuff like I don't have an ego or something. Like I don't really mind looking like an idiot to everyone else in iHop. I heard some people laughing earlier but it probably wasn't me. This is a kind of talking to myself that I haven't done in a long time. Kinda cool.

** 23:04
Markus is talking to Taylor again on facetime. Lisa tried to facetime me twice during this conversation and I denied her both times. Every time Taylor called Markus picked up. WhAT a a hoe. Friggin hoe bag.

** 23:05
Just kidding I don't really care. They aren't really talking about anything in particular though. "It's pretty nice having teeth that don't move... super jealous of your teeth" I don't even know what that conversations is but it sounds stupid. Might not be stupid though what do I know. Actually no it's stupid.

** 23:06
Bing bong bing bong. onwefinefjnefjnefjnefjnfeojnsefjonseofjnseofjnseofjnsefojnsefojnsefojnsefojnseofjnseofjnseofjnseofjnseofjnseofjnseofjnseofjnseofjnsefojnsefojnsefojnsefojnsefojnsefnojfseonjfeonjefojnsefojnsefnojsefojnesfjonsojnsefjnoefsojnsfenjoesfojnsefonjesfnojesfonjesfonj I just stood up and tried to do something totally random. He is talking about Bruce almighty. What is the deal though.

** 23:08
He doesn't know what the. "Hey I'm gonna let you go to bed are you going to be busy tomorrow" Markus did the thing where Taylor's friend talked to him and expected him to be funny or something and Taylor said Markus was hot and she was like don't steal him and lol oh my God that is so funny. This is the best thing

** 23:10
Stop I am typing on my Yes I did hear Taylor and no I don't think that I am a.

peepeepeepeepeepeepeepeepepeepeepeepee

** 23:20
Happy birthday.  

